// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.2
// source: console/resource/namespace.proto

package resource

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Namespace_List_FullMethodName       = "/api.console.resource.Namespace/List"
	Namespace_SimpleList_FullMethodName = "/api.console.resource.Namespace/SimpleList"
	Namespace_Get_FullMethodName        = "/api.console.resource.Namespace/Get"
	Namespace_Create_FullMethodName     = "/api.console.resource.Namespace/Create"
	Namespace_Update_FullMethodName     = "/api.console.resource.Namespace/Update"
	Namespace_Delete_FullMethodName     = "/api.console.resource.Namespace/Delete"
)

// NamespaceClient is the client API for Namespace service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NamespaceClient interface {
	List(ctx context.Context, in *NamespaceListRequest, opts ...grpc.CallOption) (*NamespaceListReply, error)
	SimpleList(ctx context.Context, in *NamespaceSimpleListRequest, opts ...grpc.CallOption) (*NamespaceSimpleListReply, error)
	Get(ctx context.Context, in *NamespaceGetRequest, opts ...grpc.CallOption) (*NamespaceGetReply, error)
	Create(ctx context.Context, in *NamespaceCreateRequest, opts ...grpc.CallOption) (*NamespaceCreateReply, error)
	Update(ctx context.Context, in *NamespaceUpdateRequest, opts ...grpc.CallOption) (*NamespaceUpdateReply, error)
	Delete(ctx context.Context, in *NamespaceDeleteRequest, opts ...grpc.CallOption) (*NamespaceDeleteReply, error)
}

type namespaceClient struct {
	cc grpc.ClientConnInterface
}

func NewNamespaceClient(cc grpc.ClientConnInterface) NamespaceClient {
	return &namespaceClient{cc}
}

func (c *namespaceClient) List(ctx context.Context, in *NamespaceListRequest, opts ...grpc.CallOption) (*NamespaceListReply, error) {
	out := new(NamespaceListReply)
	err := c.cc.Invoke(ctx, Namespace_List_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *namespaceClient) SimpleList(ctx context.Context, in *NamespaceSimpleListRequest, opts ...grpc.CallOption) (*NamespaceSimpleListReply, error) {
	out := new(NamespaceSimpleListReply)
	err := c.cc.Invoke(ctx, Namespace_SimpleList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *namespaceClient) Get(ctx context.Context, in *NamespaceGetRequest, opts ...grpc.CallOption) (*NamespaceGetReply, error) {
	out := new(NamespaceGetReply)
	err := c.cc.Invoke(ctx, Namespace_Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *namespaceClient) Create(ctx context.Context, in *NamespaceCreateRequest, opts ...grpc.CallOption) (*NamespaceCreateReply, error) {
	out := new(NamespaceCreateReply)
	err := c.cc.Invoke(ctx, Namespace_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *namespaceClient) Update(ctx context.Context, in *NamespaceUpdateRequest, opts ...grpc.CallOption) (*NamespaceUpdateReply, error) {
	out := new(NamespaceUpdateReply)
	err := c.cc.Invoke(ctx, Namespace_Update_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *namespaceClient) Delete(ctx context.Context, in *NamespaceDeleteRequest, opts ...grpc.CallOption) (*NamespaceDeleteReply, error) {
	out := new(NamespaceDeleteReply)
	err := c.cc.Invoke(ctx, Namespace_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NamespaceServer is the server API for Namespace service.
// All implementations must embed UnimplementedNamespaceServer
// for forward compatibility
type NamespaceServer interface {
	List(context.Context, *NamespaceListRequest) (*NamespaceListReply, error)
	SimpleList(context.Context, *NamespaceSimpleListRequest) (*NamespaceSimpleListReply, error)
	Get(context.Context, *NamespaceGetRequest) (*NamespaceGetReply, error)
	Create(context.Context, *NamespaceCreateRequest) (*NamespaceCreateReply, error)
	Update(context.Context, *NamespaceUpdateRequest) (*NamespaceUpdateReply, error)
	Delete(context.Context, *NamespaceDeleteRequest) (*NamespaceDeleteReply, error)
	mustEmbedUnimplementedNamespaceServer()
}

// UnimplementedNamespaceServer must be embedded to have forward compatible implementations.
type UnimplementedNamespaceServer struct {
}

func (UnimplementedNamespaceServer) List(context.Context, *NamespaceListRequest) (*NamespaceListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedNamespaceServer) SimpleList(context.Context, *NamespaceSimpleListRequest) (*NamespaceSimpleListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SimpleList not implemented")
}
func (UnimplementedNamespaceServer) Get(context.Context, *NamespaceGetRequest) (*NamespaceGetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedNamespaceServer) Create(context.Context, *NamespaceCreateRequest) (*NamespaceCreateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedNamespaceServer) Update(context.Context, *NamespaceUpdateRequest) (*NamespaceUpdateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedNamespaceServer) Delete(context.Context, *NamespaceDeleteRequest) (*NamespaceDeleteReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedNamespaceServer) mustEmbedUnimplementedNamespaceServer() {}

// UnsafeNamespaceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NamespaceServer will
// result in compilation errors.
type UnsafeNamespaceServer interface {
	mustEmbedUnimplementedNamespaceServer()
}

func RegisterNamespaceServer(s grpc.ServiceRegistrar, srv NamespaceServer) {
	s.RegisterService(&Namespace_ServiceDesc, srv)
}

func _Namespace_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NamespaceListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NamespaceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Namespace_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NamespaceServer).List(ctx, req.(*NamespaceListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Namespace_SimpleList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NamespaceSimpleListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NamespaceServer).SimpleList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Namespace_SimpleList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NamespaceServer).SimpleList(ctx, req.(*NamespaceSimpleListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Namespace_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NamespaceGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NamespaceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Namespace_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NamespaceServer).Get(ctx, req.(*NamespaceGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Namespace_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NamespaceCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NamespaceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Namespace_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NamespaceServer).Create(ctx, req.(*NamespaceCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Namespace_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NamespaceUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NamespaceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Namespace_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NamespaceServer).Update(ctx, req.(*NamespaceUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Namespace_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NamespaceDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NamespaceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Namespace_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NamespaceServer).Delete(ctx, req.(*NamespaceDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Namespace_ServiceDesc is the grpc.ServiceDesc for Namespace service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Namespace_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.console.resource.Namespace",
	HandlerType: (*NamespaceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Namespace_List_Handler,
		},
		{
			MethodName: "SimpleList",
			Handler:    _Namespace_SimpleList_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Namespace_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Namespace_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Namespace_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Namespace_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "console/resource/namespace.proto",
}
